df
fasf

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -524,36 +524,59 @@ jobs:
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
-              #!/bin/bash
-              export BACKEND_IP=$(aws ec2 describe-instances  --query "Reservations[*].Instances[*].PublicIpAddress"  --output text)
-              export API_URL="http://${BACKEND_IP}:3030"
-              echo "${API_URL}"
-              
-              if curl "${API_URL}/api/status" | grep "ok"
+              BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --output text)
+              export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+              echo ${BACKEND_PUBLIC_IP}
+              echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+              echo ${API_URL}
+              if curl -s $API_URL/api/status | grep "ok"
               then
-                  exit 0 
-                  #return 0
+                exit 0
               else
-                  exit 1
-                  #return 1
+                exit 1
               fi
+          #  # your code here
+          #    #!/bin/bash
+          #    export BACKEND_IP=$(aws ec2 describe-instances  --query "Reservations[*].Instances[*].PublicIpAddress"  --output text)
+          #    export API_URL="http://${BACKEND_IP}:3030"
+          #    echo "${API_URL}"
+              
+          #    if curl "${API_URL}/api/status" | grep "ok"
+          #    then
+          #        exit 0 
+          #        #return 0
+          #    else
+          #        exit 1
+          #        #return 1
+          #    fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-            #!/bin/bash
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-           
-            echo ${URL} 
-            
-            if curl -s ${URL} | grep "Welcome"
-            then
-                # Change this to 0 after the job fails
-              exit 0
-            else
-              exit 1
-            fi
+              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+              echo $FRONTEND_WEBSITE
+              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+              then
+                exit 0
+              else
+                exit 1
+              fi
+
+          #  # your code here
+          #  #!/bin/bash
+          #  URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+          # 
+          #  echo ${URL} 
+          #  
+          #  if curl -s ${URL} | grep "Welcome"
+          #  then
+          #      # Change this to 0 after the job fails
+          #    exit 0
+          #  else
+          #    exit 1
+          #  fi
       # Here's where you wil
       #- destroy_environment
       - revert-migrations
@@ -585,18 +608,20 @@ jobs:
       - run:
           name: Install dependancies - Backup Old Workflow ID to kvdb.io
           command: |
+            export OLD_WORKFLOW_ID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+            curl https://kvdb.io/8Zr83qBwdw3ySFNfLwWWk/old_workflow_id -d "${OLD_WORKFLOW_ID}"
             #export OLD_WRKFLOW_ID=$(aws cloudformation \
             #list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
             #--no-paginate --output text)
             #echo "Old Workflow ID: $OLD_WRKFLOW_ID"
             #curl https://kvdb.io/8Zr83qBwdw3ySFNfLwWWk/old_workflow_id -d "${OLD_WRKFLOW_ID}"   -k -d '1'   
-            aws cloudformation \
-            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
-            --no-paginate --output text > ~/textfile.txt
-      - persist_to_workspace:
-          root: ~/
-          paths: 
-          - textfile.txt      
+            #aws cloudformation \
+            #list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
+            #--no-paginate --output text > ~/textfile.txt
+     
       - run:
           name: Update cloudfront distribution
           command: |
@@ -618,42 +643,58 @@ jobs:
       - run:
           name: Fetch old stack workflow id
           command: |
-            # your code here
-            # Fetch the Old workflow ID
-            export OldWorkflowID=$(aws cloudformation \
-                    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                    --no-paginate --output text)
-            echo OldWorkflowID: "${OldWorkflowID}"
-            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-            # Fetch the stack names          
-            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Stack names: "${STACKS[@]}"
-
-
-
-
-
-            export STACKS_created=($(aws cloudformation list-stacks \
+             export STACKS=($(aws cloudformation list-stacks \
                 --query "StackSummaries[*].StackName" \
                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Stack names : "${STACKS_created[@]}"
-            export OldWrkflowID=$(curl --insecure https://kvdb.io/AfxCuACWvcrzuTJxyg9dLE/old_workflow_id)
-            echo Old Workflow ID: $OldWrkflowID
+             echo Stack names: "${STACKS[@]}"
+             export OldWorkflowID=$(curl --insecure https://kvdb.io/8Zr83qBwdw3ySFNfLwWWk/old_workflow_id)
+             echo Old Workflow ID: $OldWorkflowID
+
+           #  # your code here
+           #  # Fetch the Old workflow ID
+           #  export OldWorkflowID=$(aws cloudformation \
+           #          list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+           #          --no-paginate --output text)
+           #  echo OldWorkflowID: "${OldWorkflowID}"
+           #  echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+           #  # Fetch the stack names          
+           #  export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+           #          --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+           #  echo Stack names: "${STACKS[@]}"
+
+
+
+
+
+            #export STACKS_created=($(aws cloudformation list-stacks \
+            #    --query "StackSummaries[*].StackName" \
+            #    --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+            #echo Stack names : "${STACKS_created[@]}"
+            #export OldWrkflowID=$(curl --insecure https://kvdb.io/AfxCuACWvcrzuTJxyg9dLE/old_workflow_id)
+            #echo Old Workflow ID: $OldWrkflowID
       
       
       - run:
           name: Remove old stacks and files
           command: |
-            #export OldWrkflowID=$(curl --insecure https://kvdb.io/AfxCuACWvcrzuTJxyg9dLE/old_workflow_id)
-            echo Old Workflow ID: $OldWrkflowID 
-            export OldBucketID=$(cat ~/textfile.txt)
-            if [[ "${STACKS[@]}" =~ "${OldBucketID}" ]]
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/8Zr83qBwdw3ySFNfLwWWk/old_workflow_id)
+            echo Old Workflow ID: $OldWorkflowID 
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
-              aws s3 rm "s3://udapeople-${OldBucketID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldBucketID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldBucketID}"
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
             fi
+
+          #  #export OldWrkflowID=$(curl --insecure https://kvdb.io/AfxCuACWvcrzuTJxyg9dLE/old_workflow_id)
+          ##  echo Old Workflow ID: $OldWrkflowID 
+          ##  export OldBucketID=$(cat ~/textfile.txt)
+          #  if [[ "${STACKS[@]}" =~ "${OldBucketID}" ]]
+          #  then
+          #    aws s3 rm "s3://udapeople-${OldBucketID}" --recursive
+          #    aws cloudformation delete-stack --stack-name "udapeople-backend-${OldBucketID}"
+          #    aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldBucketID}"
+          #  fi
             
 ##
 workflows:
